services:
  api:
    networks:
      - asset2go-network
      - coolify

  worker:
    networks:
      - asset2go-network
      - coolify

  web:
    networks:
      - asset2go-network
      - coolify

networks:
  coolify:
    external: true
